default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 5.0e4
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
            
HunterBrain:
    batch_size: 128
    buffer_size: 512
    use_recurrent: false
    max_steps: 2.0e5
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity:
            strength: 0.05
            gamma: 0.99
            encoding_size: 64
        gail:
            strength: 0.05
            gamma: 0.9
            encoding_size: 64
            demo_path: demos/HunterAgent.demo
    
PreyBrain:
    batch_size: 128
    buffer_size: 512
    use_recurrent: false
    max_steps: 2.0e5